# Generated by Django 3.2.9 on 2022-04-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220417_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='store/close-icon.png', null=True, upload_to='store/'),
        ),
    ]
